version: '3.8'

services:
  # Laravel PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app:11
    container_name: laravel_app
    volumes:
      - ../.:/var/www/html
      - .././php.ini:/usr/local/etc/php/php.ini
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - laravel-network

  # Nginx Server
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../.:/var/www/html
    depends_on:
      - app
    networks:
      - laravel-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravel_phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - laravel-network

volumes:
  mysql-data:

networks:
  laravel-network:
